bundle:
  version: 6.5.0-eng-3686
  olmDisabled: true
  communityOnly: true
  containerRegistry: registry.connect.redhat.com
operator:
  generateClusterRoles: false
  namespacePlaceholder: entando-cluster-operator
  imagePullSecrets:
    - redhat-registry
    - entando-pull-secret
  relatedImages:
    rhel8_mysql_80:
      sha256: 1dfdc3499ec8dea5d9a275214b498dd1ea13464dbefa8bdae4e6d42c6692b4c6
      version: 1-189
      registry: registry.redhat.io
      organization: rhel8
      repository: mysql80
    rhel8_postgresql_12:
      sha256: fa920188f567e51d75aacd723f0964026e42ac060fed392036e8d4b3c7a8129f
      version: 1-109
      registry: registry.redhat.io
      organization: rhel8
      repository: postgresql-12
    app_builder_6_3:
      sha256: 3bc6411823e01931328b4a696b9751750060af51577108bd628981ad71ba54ed
      version: 6.3.93-hotfix.1
    app_builder_6_4:
      sha256: 3bc6411823e01931328b4a696b9751750060af51577108bd628981ad71ba54ed
      version: 6.3.93-hotfix.1
    busybox:
      sha256: 14d4f50961544fdb669075c442509f194bdc4c0e344bde06e35dbd55af842a38
      version: latest
    entando_avatar_plugin:
      sha256: 3ff5425ca1b27c609614879bf1c8a25df4e6c0c560caa683d272eccd6090cee6
      version: 6.0.5
    entando_component_manager_6_3:
      sha256: d48eacfe8a123aefac60390b5417da1ec5aab0378c21fadb66b567adde01ce61
      version: 6.3.26-fix.1
    entando_component_manager_6_4:
      sha256: 6dfa8c2c910e0d36feee404fa72fafc81d138607724fc5a017aeea461716ceba
      version: 7.0.2
    entando_de_app_eap_6_3:
      sha256: 8b5657c42b435cb5e22d40b783a5c69afeb63d7c9d14b201ca16fce91f4c06f5
      version: 6.3.68-fix.3-ENG-3332-PR-335
    entando_de_app_eap_6_4:
      sha256: 71c13bca21b52a8cbad26fe11dac6250a938d3d6fc5aecfe245d604bbc509914
      version: 6.3.68-fix.3-ENG-3332-PR-335
    entando_de_app_wildfly_6_3:
      sha256: 71c13bca21b52a8cbad26fe11dac6250a938d3d6fc5aecfe245d604bbc509914
      version: 6.3.68-fix.3-ENG-3332-PR-335
    entando_de_app_wildfly_6_4:
      sha256: 71c13bca21b52a8cbad26fe11dac6250a938d3d6fc5aecfe245d604bbc509914
      version: 6.3.68-fix.3-ENG-3332-PR-335
    entando_k8s_app_controller:
      sha256: 1308a2c1e56ecc13e47da5a399c6fb9a28e9adf2d5fde2530331b7c5dda3cca1
      version: 7.0.2
    entando_k8s_app_plugin_link_controller:
      sha256: bf71073f3e4d6c6815cbdc582a984695b5944cf3c82e603386a96bc0a1b4bd74
      version: 7.0.2
    entando_k8s_cluster_infrastructure_controller:
      sha256: 86dbea6696349d7b2393e12bacef4d1acec2dd3f8551e397fa26c92706a18dd3
      version: 6.3.7
    entando_k8s_composite_app_controller:
      sha256: 4bc6797bb41b3e407b64530c3cff7a78f3fc2c22863caad9c606ccd650310b61
      version: 6.3.11
    entando_k8s_controller_coordinator:
      sha256: 4c225f00914cb8db345358e9bfb2e2dce3370b5b51189d552b9f2fd3646cc666
      version: 7.0.2-ENG-3686
    entando_k8s_database_service_controller:
      sha256: d6ca8e1c9b1b257bf6234205852557d20605aa6e3e968e1a304360f3db03e78d
      version: 7.0.2
    entando_k8s_dbjob:
      sha256: 144b206d9643c101914b7e6cc9bd091cf2f4409f145ccb839829fbe2d5569b9f
      version: 7.0.2
    entando_k8s_keycloak_controller:
      sha256: c23248ae0a35dab52edd76e3f65e35625faa293d6c13f389d650535f89cd42cc
      version: 7.0.2-ENG-3691-PR-53
    entando_k8s_plugin_controller:
      sha256: 8fa2a1f44ca9b94797bb5d65d409c58d924cabb60dada6bd2cb1a654adf605e3
      version: 7.0.2
    entando_k8s_service:
      sha256: d1e022d6c1eb1f20268372493115fb34066b52245995eee11b77b7c36bc66431
      version: 7.0.2
    entando_process_driven_plugin:
      sha256: 18db1afb892393c1dcf7c36e5a4bbd1d6bc60029014094178ce1acb5dd1f68a4
      version: 6.0.50-fix.1
    entando_keycloak:
      sha256: 36383301348c15526deac7d378a2f1a8a216c419697f3255e6d183a9cd53e323
      version: 6.3.9
    entando_redhat_sso:
      sha256: 3692adb3694b3bf278bed7a678c9d0eaa0aba8e3e3ed4117ca04156525bcac72
      version: 6.3.9
    mysql_80_centos7:
      sha256: c1ff5d9af7bb39556a70a5983284956d86f4416c910d36962b71048f8c6a2b11
      version: 20210423-5849b27
      organization: centos
      repository: mysql-80-centos7
    postgresql_12_centos7:
      sha256: be8803d45d64870f8dfd018f3110af62e2e1558d64191faea461005e1bd03243
      version: 20210722-70dc4d3
      organization: centos
      repository: postgresql-12-centos7
