bundle:
  version: 7.2.1
  olmDisabled: true
  communityOnly: true
  containerRegistry: registry.connect.redhat.com
operator:
  generateClusterRoles: false
  namespacePlaceholder: entando-cluster-operator
  imagePullSecrets:
    - redhat-registry
    - entando-pull-secret
  relatedImages:
    rhel8_mysql_80:
      sha256: 1def587ff04c2a7736bcd4764c1fb50b0613aa915a3e7aeec5087e2a546275c7
      version: 8.0.29
    rhel8_postgresql_12:
      sha256: 5da64777195aba69c4d5cfaa27a87d376d43c9fb5c0e25afa985c41ea356b050
      version: 14.1.0
    app_builder_6_3:
      sha256: 3bc6411823e01931328b4a696b9751750060af51577108bd628981ad71ba54ed
      version: 6.3.93-hotfix.1
    app_builder_6_4:
      sha256: 93827609d1aa4ad2454f586f136f396af356b5112eaa8191ebcae14dba44dbec
      version: 7.2.1-rc2
    busybox:
      sha256: 14d4f50961544fdb669075c442509f194bdc4c0e344bde06e35dbd55af842a38
      version: latest
    entando_avatar_plugin:
      sha256: 3ff5425ca1b27c609614879bf1c8a25df4e6c0c560caa683d272eccd6090cee6
      version: 6.0.5
    entando_component_manager_6_3:
      sha256: d48eacfe8a123aefac60390b5417da1ec5aab0378c21fadb66b567adde01ce61
      version: 6.3.26-fix.1
    entando_component_manager_6_4:
      sha256: a06cab977fe9a5f89996ed44da5446880e220324fbf6bd9e4698f41af9a0d26f
      version: 7.2.1-ENGPM-546-rc1
    entando_de_app_eap_6_3:
      sha256: 8b5657c42b435cb5e22d40b783a5c69afeb63d7c9d14b201ca16fce91f4c06f5
      version: 6.3.68-fix.3-ENG-3332-PR-335
    entando_de_app_eap_6_4:
      sha256: f4c51fef81a832933c8dec6b3b20341f84246c40ca2afcaca190f724b4040f92
      version: 7.2.1-rc2
    entando_de_app_wildfly_6_3:
      sha256: 71c13bca21b52a8cbad26fe11dac6250a938d3d6fc5aecfe245d604bbc509914
      version: 6.3.68-fix.3-ENG-3332-PR-335
    entando_de_app_wildfly_6_4:
      sha256: cf5365d6db27b2a8823d09bf85d858f39d6b8452d85db7112c0e22a8619ffdf0
      version: 7.2.1-rc2
    entando_de_app_tomcat_6_4:
      sha256: 6fbb6c324d6313970b478f68c1a65f32c71a9b079b7280441a1db583bd1b803d
      version: 7.2.1-rc2
    entando_k8s_app_controller:
      sha256: 3c90051116f39a5f54aceef331006dd36c589061980587edad550cf223ef1353
      version: 7.2.0
    entando_k8s_app_plugin_link_controller:
      sha256: f506c4184e89cbb007b51ca3c0350fcb09d22218e55d1046ec959cb875e7fe17
      version: 7.2.0
    entando_k8s_cluster_infrastructure_controller:
      sha256: 86dbea6696349d7b2393e12bacef4d1acec2dd3f8551e397fa26c92706a18dd3
      version: 6.3.7
    entando_k8s_composite_app_controller:
      sha256: 4bc6797bb41b3e407b64530c3cff7a78f3fc2c22863caad9c606ccd650310b61
      version: 6.3.11
    entando_k8s_controller_coordinator:
      sha256: e5d38d61aa6176b65cad9df4dadcff4e760e2f3897842811eeb492dcc11a3aef
      version: 7.2.0
    entando_k8s_database_service_controller:
      sha256: 9205f0eed6c4ceea643e87db5398a155a001112b7d6f2bc772aed98f3ceda416
      version: 7.2.0
    entando_k8s_dbjob:
      sha256: d05ee184e833fd7e614c62700ae6816a29da8f70ec836c84f96c2a00a791a29a
      version: 7.1.1
    entando_k8s_keycloak_controller:
      sha256: e321fac37d1002336a76b5ec76641bb4a077214140a81c41b0c52f5a1f28192b
      version: 7.2.0
    entando_k8s_plugin_controller:
      sha256: 64a3c9d71ab0d40dbec12e741b3b1875a969da08a517e97d8314642fbee2b839
      version: 7.2.0
    entando_k8s_service:
      sha256: f90e82c4625624a5af12c0522356daca5ffb91abd07c88bb81b2aa0e8d027fb2
      version: 7.1.2
    entando_process_driven_plugin:
      sha256: 18db1afb892393c1dcf7c36e5a4bbd1d6bc60029014094178ce1acb5dd1f68a4
      version: 6.0.50-fix.1
    entando_keycloak:
      sha256: 5964ebb828497e8e459878dcd7115904b7113cad962b5d61e1e93e84826ca004
      version: 7.2.0
    entando_redhat_sso:
      sha256: e8c9e9e193a6dbc9ea171497b5b6768f442f31e465d67e961eb7553bdcaddf18
      version: 7.2.0
    mysql_80_centos7:
      sha256: 62c60139c609d69d135815e6ab59cc73933ef476aafbf51d2bdedaed3b950147
      version: 8.0.29
    postgresql_12_centos7:
      sha256: 62c4a020c772a0107b1d64302e3022ea413dbeba72b061acae41f98f4230337f
      version: 14.1.0
