bundle:
  version: 7.1.6
  olmDisabled: true
  communityOnly: true
  containerRegistry: registry.connect.redhat.com
operator:
  generateClusterRoles: false
  namespacePlaceholder: entando-cluster-operator
  imagePullSecrets:
    - redhat-registry
    - entando-pull-secret
  relatedImages:
    rhel8_mysql_80:
      sha256: 1def587ff04c2a7736bcd4764c1fb50b0613aa915a3e7aeec5087e2a546275c7
      version: 8.0.29
    rhel8_postgresql_12:
      sha256: 5da64777195aba69c4d5cfaa27a87d376d43c9fb5c0e25afa985c41ea356b050
      version: 14.1.0
    app_builder_6_3:
      sha256: 3bc6411823e01931328b4a696b9751750060af51577108bd628981ad71ba54ed
      version: 6.3.93-hotfix.1
    app_builder_6_4:
      sha256: 07a39391f627990a3f663efe649d4a8d514ec9a88a01be21051f47740358f095
      version: 7.1.5
    busybox:
      sha256: 14d4f50961544fdb669075c442509f194bdc4c0e344bde06e35dbd55af842a38
      version: latest
    entando_avatar_plugin:
      sha256: 3ff5425ca1b27c609614879bf1c8a25df4e6c0c560caa683d272eccd6090cee6
      version: 6.0.5
    entando_component_manager_6_3:
      sha256: d48eacfe8a123aefac60390b5417da1ec5aab0378c21fadb66b567adde01ce61
      version: 6.3.26-fix.1
    entando_component_manager_6_4:
      sha256: 2944b0471f2272acb112f2b7312c746aea0e6d6a8e8ee9b6ef81545e4d25f411
      version: 7.1.5
    entando_de_app_eap_6_3:
      sha256: 8b5657c42b435cb5e22d40b783a5c69afeb63d7c9d14b201ca16fce91f4c06f5
      version: 6.3.68-fix.3-ENG-3332-PR-335
    entando_de_app_eap_6_4:
      sha256: b673aa635498e6893c2194751e528c12787e1ff65d7e01e31969d40d29921be7
      version: 7.1.5
    entando_de_app_wildfly_6_3:
      sha256: 71c13bca21b52a8cbad26fe11dac6250a938d3d6fc5aecfe245d604bbc509914
      version: 6.3.68-fix.3-ENG-3332-PR-335
    entando_de_app_wildfly_6_4:
      sha256: 640ccd5c27b0cc6e45a3f5b219c8c43d3d504325db2758d3e30a3957c6f1de06
      version: 7.1.5
    entando_de_app_tomcat_6_4:
      sha256: faed903163690bc1dd08a8a96cb1e60291fbba369590c1615ab75562afa08ca1
      version: 7.1.5
    entando_k8s_app_controller:
      sha256: 2782b20f24b34c014bb3b0f0f832abe467eed0884a6e27f7ad77de470ef7e2d6
      version: 7.1.6
    entando_k8s_app_plugin_link_controller:
      sha256: d9e9cdcbf2abec4b0d1253955d4dffd01de284d32f40ac42ec18aa3e94e32db4
      version: 7.1.0
    entando_k8s_cluster_infrastructure_controller:
      sha256: 86dbea6696349d7b2393e12bacef4d1acec2dd3f8551e397fa26c92706a18dd3
      version: 6.3.7
    entando_k8s_composite_app_controller:
      sha256: 4bc6797bb41b3e407b64530c3cff7a78f3fc2c22863caad9c606ccd650310b61
      version: 6.3.11
    entando_k8s_controller_coordinator:
      sha256: 0ac2696c3694b03d76fecb4941dfe91fab13489611eb5825deec7e4badf54e4b
      version: 7.1.6
    entando_k8s_database_service_controller:
      sha256: 5366bc2d847ca6a4d68eaa516082991a6b4affc802d5b8ea5a0a33bfbdc8aa68
      version: 7.1.1
    entando_k8s_dbjob:
      sha256: d05ee184e833fd7e614c62700ae6816a29da8f70ec836c84f96c2a00a791a29a
      version: 7.1.1
    entando_k8s_keycloak_controller:
      sha256: 9d6c62787a6eeb1000e0ddec5a35e327a175a67e5126f18e18b3e0b629094404
      version: 7.1.1
    entando_k8s_plugin_controller:
      sha256: 1084d03bd9ecf2a720390b7e1543f60b43c4baa523b97a85e7e54590d81d2574
      version: 7.1.1
    entando_k8s_service:
      sha256: f90e82c4625624a5af12c0522356daca5ffb91abd07c88bb81b2aa0e8d027fb2
      version: 7.1.2
    entando_process_driven_plugin:
      sha256: 18db1afb892393c1dcf7c36e5a4bbd1d6bc60029014094178ce1acb5dd1f68a4
      version: 6.0.50-fix.1
    entando_keycloak:
      sha256: 4b5b81a6f233e070a747541ec1fa30cdaeca78feefa1542cb117aaaf2079863c
      version: 7.1.1
    entando_redhat_sso:
      sha256: b5afae1e933d432ccab84e31a9140f8fd2a51517b95a3a373a29bbe88a62d900
      version: 7.1.1
    mysql_80_centos7:
      sha256: 62c60139c609d69d135815e6ab59cc73933ef476aafbf51d2bdedaed3b950147
      version: 8.0.29
    postgresql_12_centos7:
      sha256: 62c4a020c772a0107b1d64302e3022ea413dbeba72b061acae41f98f4230337f
      version: 14.1.0
