---
# Source: entando-k8s-operator-bundle/templates/docker-image-info-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: entando-docker-image-info
data:
  image-name: >-
    {"version":"6.1.353","executable-type":"jvm","registry":"docker.io","organization":"entando"}
