{{- if not .Values.bundle.olmDisabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: entando-docker-image-info
data:
  image-name: >-
    {"version":"6.1.353","executable-type":"jvm","registry":"docker.io","organization":"entando"}
{{- end }}